[package]
name = "forge"
version.workspace = true
edition.workspace = true

[dependencies]
blake3.workspace = true
tree-sitter.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]
tree-sitter-python.workspace = true
